name: Frontend

on:
  push:
    branches: [ "main", "develop", "feature/*" ]
  pull_request:
    branches: [ "main", "develop", "feature/*" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: src/http/frontend/package-lock.json

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: src/http/frontend

      # Step 4: Run linting
      - name: Run lint check
        run: npm run lint
        working-directory: src/http/frontend

  check-format:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: src/http/frontend/package-lock.json

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: src/http/frontend

      # Step 4: Run format check
      - name: Run format check
        run: npm run check-format
        working-directory: src/http/frontend
